### ISSUE TITLE
Error when importing a code with a top level method named 'init' to a component.

### ISSUE THREAD

**Issue by ntaoo** [dart-lang/angular2#181]
I got a runtime error as below, 

```
ORIGINAL EXCEPTION: No top-level method 'init' with matching arguments declared.

NoSuchMethodError: incorrect number of arguments passed to method named 'init'
Receiver: top-level
Tried calling: init(Instance(length:0) of '_GrowableList', Instance(length:3) of '_GrowableList', Instance(length:0) of '_GrowableList')
Found: init()

```
I get this error after upgrading angular2 from beta.22 to 2.0.0.
I suspect [this commit](https://github.com/dart-lang/angular2/commit/8cd7f35d74a9a8e323d6f0cf73ddda5acb079fe3#diff-ee27b8acd84dc52a6e6ca9be762a0b37R719). 

Here is a repository with minimum code reproducing this error.
https://github.com/ntaoo/ng2_init_method_issue

The workaround is to add a prefix to import statement (ex: below's example, "import 'model.dart' as m;").
https://github.com/ntaoo/ng2_init_method_issue/blob/master/lib/app_component.dart

Originally, I got this error with gapi.auth2.init with package:js.
https://github.com/ntaoo/ng2_g_signin/issues/1

**Comment by matanlurey** [comment]
OK, so this is because `init` conflicts with generated code.

Please import your code with a prefix or rename init to something else.

**Comment by ntaoo** [comment]
O.K, thank you for checking:) Any chance to add documentation or warning for this reserved method?
